export const appRouter = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/login/forgot-password',
  preferences: '/register/preferences',
  userType: '/register/user-type',
  models: '/models',
  addNudes: '/account/nudes',
  editProfile: '/account/profile/edit',
  becomeCreator: '/account/become-creator',
  becomeCreatorEmail: '/account/become-creator/email',
  becomeCreatorIdentity: '/account/become-creator/identity',
  conversations: '/account/conversations',
  settingsConversations: '/account/settings/conversations',
};
