export const appRouter = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/login/forgot-password',
  preferences: '/register/preferences',
  userType: '/register/user-type',
  models: '/models',
  addNudes: '/account/nudes',
  myProfile: '/account/settings/my-profile',
  becomeCreator: '/account/become-creator',
  becomeCreatorEmail: '/account/become-creator/email',
  becomeCreatorIdentity: '/account/become-creator/identity',
  becomeCreatorContentProviderPolicy:
    '/account/become-creator/content-provider-policy',
  conversations: '/account/conversations',
  settingsConversations: '/account/settings/conversations',
  settingsPayment: '/account/settings/payment',
  settingsPreferences: '/account/settings/preferences',
  revenue: '/account/revenue',
};
